### ISSUE TITLE
xml_write() should support setting the root element name

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-XML#22]
In the current version of xml_write the root element is always called `<root>`. 

```
xml_write(marc)
````

If `marc` contains something like:

```
marc:
 record:
   controlfield: ...
   datafileld: ....
```

The fix will currently result in:

```
<root><record><controlfield>...</controlfield><datafield>...</datafield></root>
```

which need to be processed regex search/replace to create the correct '<marc>' root element.
